#!/usr/bin/env bash

# プロジェクト完了レポート生成スクリプト

if [ $# -lt 1 ]; then
    echo "Usage: $0 <project_name>"
    exit 1
fi

PROJECT_NAME=$1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$BASE_DIR/deliverables/$PROJECT_NAME"
REPORTS_DIR="$BASE_DIR/logs/reports"

mkdir -p "$REPORTS_DIR"

if [ ! -d "$PROJECT_DIR" ]; then
    echo "Error: Project directory '$PROJECT_DIR' does not exist"
    exit 1
fi

REPORT_FILE="$REPORTS_DIR/${PROJECT_NAME}_completion_report.md"

echo "📊 Generating completion report for: $PROJECT_NAME"

# レポート生成
cat > "$REPORT_FILE" << EOF
# 🎉 プロジェクト完了レポート

## プロジェクト情報
- **プロジェクト名**: $PROJECT_NAME
- **完了日時**: $(date '+%Y年%m月%d日 %H:%M:%S')
- **成果物パス**: \`deliverables/$PROJECT_NAME/\`

## 📁 生成ファイル一覧
EOF

# ファイル一覧を追加
echo "" >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"
cd "$PROJECT_DIR"
find . -type f -name "*.md" -o -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.json" -o -name "*.yaml" -o -name "*.yml" | sort >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"

# ディレクトリ構造を追加
echo "" >> "$REPORT_FILE"
echo "## 📂 ディレクトリ構造" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"
tree -I 'node_modules|.git|__pycache__|.next|dist|build' -L 3 2>/dev/null || find . -type d | head -20 | sort >> "$REPORT_FILE"
echo "\`\`\`" >> "$REPORT_FILE"

# READMEの内容を取得
if [ -f "README.md" ]; then
    echo "" >> "$REPORT_FILE"
    echo "## 📖 プロジェクト概要" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    head -20 "README.md" >> "$REPORT_FILE"
fi

# RELEASE.mdの内容を取得
if [ -f "RELEASE.md" ]; then
    echo "" >> "$REPORT_FILE"
    echo "## 🚀 リリース情報" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    head -20 "RELEASE.md" >> "$REPORT_FILE"
fi

# Git統計
if [ -d ".git" ]; then
    echo "" >> "$REPORT_FILE"
    echo "## 📈 開発統計" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "- **総コミット数**: $(git rev-list --count HEAD 2>/dev/null || echo 'N/A')" >> "$REPORT_FILE"
    echo "- **ファイル数**: $(find . -type f | wc -l | tr -d ' ')" >> "$REPORT_FILE"
    echo "- **コード行数**: $(find . -name "*.py" -o -name "*.js" -o -name "*.ts" | xargs wc -l 2>/dev/null | tail -1 | awk '{print $1}' || echo 'N/A')" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "---" >> "$REPORT_FILE"
echo "*Generated by Claude Autodev Master Monitor*" >> "$REPORT_FILE"

echo "✅ Report generated: $REPORT_FILE"
echo "📄 Report summary:"
echo "   - Files: $(find "$PROJECT_DIR" -type f | wc -l | tr -d ' ')"
echo "   - Directories: $(find "$PROJECT_DIR" -type d | wc -l | tr -d ' ')"