#!/usr/bin/env bash

# LINE通知送信スクリプト

if [ $# -lt 1 ]; then
    echo "Usage: $0 <project_name>"
    exit 1
fi

PROJECT_NAME=$1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$BASE_DIR/deliverables/$PROJECT_NAME"
REPORTS_DIR="$BASE_DIR/logs/reports"

# LINE Bot設定
CHANNEL_ACCESS_TOKEN="FzpiO7StfY1GtQ1URU5um4IiwXipxgM+bZeuMd1h2b947eoy4doDrd96Sw9x8VKix/aYs4T3zkNL/vZRHo20bF28t35D1urum/WptrpnEthFZUFAR3NpBxc0kQ6U9Q2wXZ6422tOx/5nRCkn5qtsIAdB04t89/1O/w1cDnyilFU"
DESTINATION_USER_ID="U2f0d021267564d91134b178d7f65fc84"

# 直接LINE API呼び出し関数
send_direct_line_message() {
    local msg="$1"
    
    # JSON エスケープ
    escaped_msg=$(echo "$msg" | sed 's/"/\\"/g' | sed 's/$/\\n/' | tr -d '\n' | sed 's/\\n$//')
    
    curl -X POST https://api.line.me/v2/bot/message/push \
        -H "Authorization: Bearer $CHANNEL_ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
            \"to\": \"$DESTINATION_USER_ID\",
            \"messages\": [{
                \"type\": \"text\",
                \"text\": \"$escaped_msg\"
            }]
        }" \
        -s -o /dev/null
    
    if [ $? -eq 0 ]; then
        echo "✅ LINE notification sent successfully via direct API"
    else
        echo "❌ Failed to send LINE notification"
    fi
}

echo "📱 Sending LINE notification for: $PROJECT_NAME"

# プロジェクト情報を収集
completion_time=$(date '+%Y/%m/%d %H:%M')
file_count=$(find "$PROJECT_DIR" -type f 2>/dev/null | wc -l | tr -d ' ')
has_readme=$([ -f "$PROJECT_DIR/README.md" ] && echo "✅" || echo "❌")
has_tests=$([ -d "$PROJECT_DIR/tests" ] && echo "✅" || echo "❌")

# メッセージ作成
message="🎉 プロジェクト完了通知

📋 プロジェクト: $PROJECT_NAME
⏰ 完了時刻: $completion_time
📁 生成ファイル数: $file_count
📖 README: $has_readme
🧪 テスト: $has_tests

🔗 パス: deliverables/$PROJECT_NAME/

Generated by Claude Autodev 🤖"

# Claude Code の MCP サーバーを使用してLINE通知を送信
echo "Attempting to send notification via Claude Code MCP..."

# 一時的なJSONファイルを作成
temp_json=$(mktemp)
cat > "$temp_json" << EOF
{
  "message": "$message",
  "userId": "$DESTINATION_USER_ID"
}
EOF

# Claude Code経由で送信を試行
if command -v claude >/dev/null 2>&1; then
    echo "📤 Sending via Claude Code MCP..."
    claude --prompt "Use the LINE MCP server to send the following message to user $DESTINATION_USER_ID: $message" 2>/dev/null
    
    if [ $? -eq 0 ]; then
        echo "✅ LINE notification sent successfully via Claude Code MCP"
    else
        echo "⚠️  Claude Code MCP method failed, trying direct API..."
        # 直接API呼び出しにフォールバック
        send_direct_line_message "$message"
    fi
else
    echo "⚠️  Claude CLI not found, trying direct API..."
    send_direct_line_message "$message"
fi

# 通知ログに記録
echo "$(date): Sent notification for $PROJECT_NAME" >> "$BASE_DIR/logs/notifications.log"

rm -f "$temp_json"