#!/usr/bin/env bash

# LINE通知送信スクリプト

if [ $# -lt 1 ]; then
    echo "Usage: $0 <project_name>"
    exit 1
fi

PROJECT_NAME=$1
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
BASE_DIR="$(dirname "$SCRIPT_DIR")"
PROJECT_DIR="$BASE_DIR/deliverables/$PROJECT_NAME"
REPORTS_DIR="$BASE_DIR/logs/reports"

# LINE Bot設定
CHANNEL_ACCESS_TOKEN="FzpiO7StfY1GtQ1URU5um4IiwXipxgM+bZeuMd1h2b947eoy4doDrd96Sw9x8VKix/aYs4T3zkNL/vZRHo20bF28t35D1urum/WptrpnEthFZUFAR3NpBxc0kQ6U9Q2wXZ6422tOx/5nRCkn5qtsIAdB04t89/1O/w1cDnyilFU"
DESTINATION_USER_ID="U2f0d021267564d91134b178d7f65fc84"

# 直接LINE API呼び出し関数
send_direct_line_message() {
    local msg="$1"
    
    # JSON エスケープ
    escaped_msg=$(echo "$msg" | sed 's/"/\\"/g' | sed 's/$/\\n/' | tr -d '\n' | sed 's/\\n$//')
    
    curl -X POST https://api.line.me/v2/bot/message/push \
        -H "Authorization: Bearer $CHANNEL_ACCESS_TOKEN" \
        -H "Content-Type: application/json" \
        -d "{
            \"to\": \"$DESTINATION_USER_ID\",
            \"messages\": [{
                \"type\": \"text\",
                \"text\": \"$escaped_msg\"
            }]
        }" \
        -s -o /dev/null
    
    if [ $? -eq 0 ]; then
        echo "✅ LINE notification sent successfully via direct API"
    else
        echo "❌ Failed to send LINE notification"
    fi
}

echo "📱 Sending LINE notification for: $PROJECT_NAME"

# プロジェクト情報を収集
completion_time=$(date '+%Y/%m/%d %H:%M')
file_count=$(find "$PROJECT_DIR" -type f 2>/dev/null | wc -l | tr -d ' ')
has_readme=$([ -f "$PROJECT_DIR/README.md" ] && echo "✅" || echo "❌")
has_tests=$([ -d "$PROJECT_DIR/tests" ] && echo "✅" || echo "❌")

# メッセージ作成
message="🎉 プロジェクト完了通知

📋 プロジェクト: $PROJECT_NAME
⏰ 完了時刻: $completion_time
📁 生成ファイル数: $file_count
📖 README: $has_readme
🧪 テスト: $has_tests

🔗 パス: deliverables/$PROJECT_NAME/

Generated by Claude Autodev 🤖"

# Pythonスクリプト経由でLINE通知を送信
echo "📤 Sending via Python LINE Messaging API script..."

# サマリー情報を作成
summary="📁 ファイル数: $file_count | 📖 README: $has_readme | 🧪 テスト: $has_tests"

if python3 "$SCRIPT_DIR/send_line_message.py" "$PROJECT_NAME" "$summary"; then
    echo "✅ LINE notification sent successfully via Python script"
else
    echo "⚠️  LINE API failed, sending local notification..."
    # ローカル通知にフォールバック
    "$SCRIPT_DIR/send_local_notification.sh" "$PROJECT_NAME" "$summary"
    
    # 最後の手段として直接API試行
    echo "Also trying direct API call..."
    send_direct_line_message "$message"
fi

# Slack通知も送信
echo "📤 Sending Slack notification..."
if python3 "$SCRIPT_DIR/send_slack_message.py" "$PROJECT_NAME" "$summary"; then
    echo "✅ Slack notification sent successfully"
else
    echo "⚠️  Slack notification failed (webhook not configured or error)"
fi

# 常にローカル通知も送信（重要なプロジェクト完了を見逃さないため）
"$SCRIPT_DIR/send_local_notification.sh" "$PROJECT_NAME" "$summary"

# 通知ログに記録
echo "$(date): Sent notification for $PROJECT_NAME" >> "$BASE_DIR/logs/notifications.log"

rm -f "$temp_json"